# Generated by Django 4.0 on 2023-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='date',
            field=models.DateField(default="2023-1-1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='summary',
            field=models.TextField(),
        ),
    ]
